language: node_js

node_js:
  - "6"
services:
  
before_install:
  - travis_wait npm install

cache:
  - node_modules

script: 
  - npm test

env:
 CODECLIMATE_REPO_TOKEN: 680a1143d7c73e297ea0f844b0ac79e23cfd06b34c9717e813de2523c2d507a3

after_success:
  - nyc npm run test && nyc report --reporter=text-lcov | coveralls